# SPDX-License-Identifier: MIT
"""D6: memo export, with the AI-DRAFT watermark (STEP-05 3.3, D6).

STEP-05 3.3: "Unsigned memos render with a persistent AI-DRAFT watermark in all
exports (md, html)." ARCHITECTURE 8.4 gives the reason: memos are labeled as
AI-drafted until human-signed, which is the EU AI Act transparency pattern.

There is no way to turn it off
------------------------------
The rendering functions take a memo and an **optional signature**, and nothing
else. There is no ``watermark=False``, no ``suppress_label``, no "internal
copy" mode. Whether the watermark appears is a function of whether a signature
was supplied, and a caller that wants an unmarked export has to produce a real
signature to get one.

This is the shape ``ReviewOutcome.attribution`` uses, and it is deliberate for
the same reason: a label that can be switched off is a label that will be
switched off, and the one moment it matters is the moment somebody wanted it
gone. A test asserts that no parameter of any exported function can remove it,
by rendering with every signature value there is (one, and none).

A supplied signature is checked, not trusted
--------------------------------------------
Passing a signature does not remove the watermark by itself: the signature has
to actually cover this memo's digest. A signature over some other memo leaves
the watermark in place *and* says so, because the alternative is an export that
looks finalized on the strength of a signature belonging to a different
document.
"""

import html
from pathlib import Path

from ts_sentry.agents.memo.memo import Memo, MemoStatus, SentenceRole
from ts_sentry.orchestrator.signing import SignedMemo

__all__ = [
    "WATERMARK",
    "render_html",
    "render_markdown",
    "write_memo_html",
    "write_memo_markdown",
]

WATERMARK = "AI-DRAFT - NOT A DECISION - generated by an AI agent, not signed by a human analyst"
"""The label an unsigned memo carries in every export.

Written out rather than assembled, so a grep for the exact string finds every
place it is emitted and a test can assert it appears.
"""

_ROLE_HEADINGS = {
    SentenceRole.FACT: "Facts relied on (DSA Art. 17(3)(b))",
    SentenceRole.POLICY_GROUND: "Contractual ground (DSA Art. 17(3)(e))",
    SentenceRole.MEASURE: "Measure proposed (DSA Art. 17(3)(a))",
    SentenceRole.REDRESS: "Redress available (DSA Art. 17(3)(f))",
}


def _signature_covers(memo: Memo, signed: SignedMemo | None) -> bool:
    """Whether ``signed`` is a signature over *this* memo.

    A signature over a different memo is treated exactly as no signature, plus a
    stated mismatch. Rendering it as finalized would let one signed memo
    authenticate another.
    """
    if signed is None:
        return False
    return signed.signature.subject_hash == memo.content_digest and memo.status is MemoStatus.SIGNED


def _status_lines(memo: Memo, signed: SignedMemo | None) -> list[str]:
    """The status block, which every export opens with."""
    if _signature_covers(memo, signed):
        assert signed is not None  # _signature_covers is False for None
        return [
            "**SIGNED STATEMENT OF REASONS**",
            "",
            f"- Signed by: `{signed.signature.analyst_id}`",
            f"- Decision: `{signed.signature.decision.value}`",
            f"- Signed at: {signed.signature.signed_ts.isoformat()}",
            f"- Signature: `{signed.signature.signature_hash}`",
            f"- Over memo digest: `{memo.content_digest}`",
        ]

    lines = [f"**{WATERMARK}**"]
    if signed is not None:
        lines += [
            "",
            "> A signature was supplied and does **not** cover this memo: it is over "
            f"`{signed.signature.subject_hash[:16]}...` and this memo digests to "
            f"`{memo.content_digest[:16]}...`. The memo is rendered as an unsigned draft.",
        ]
    return lines


def render_markdown(memo: Memo, signed: SignedMemo | None = None) -> str:
    """Render a memo as Markdown.

    Two parameters, and neither of them can suppress the watermark.
    """
    lines: list[str] = [
        f"# Statement of reasons: {memo.memo_id}",
        "",
        *_status_lines(memo, signed),
        "",
        "## Subject",
        "",
        f"- Case: `{memo.case_id}`",
        f"- Subject: `{memo.subject_id}`",
        f"- Evidence pack digest: `{memo.pack_digest}`",
        f"- Policy corpus: `{memo.corpus_version}` (`{memo.corpus_sha256}`)",
        "",
        "## Use of automated means (DSA Art. 17(3)(c))",
        "",
        f"- Content identified by automated means: "
        f"{'yes' if memo.automated_means.detection_automated else 'no'}",
        f"- Decision: `{memo.automated_means.decision.value}`",
        f"- Drafted by: `{memo.automated_means.drafted_by}`",
    ]

    for role in SentenceRole:
        sentences = [s for s in memo.sentences if s.role is role]
        if not sentences:
            continue
        lines += ["", f"## {_ROLE_HEADINGS[role]}", ""]
        for sentence in sentences:
            lines.append(f"{sentence.index + 1}. {sentence.text}")
            if sentence.evidence_ids:
                lines.append(
                    f"   - Evidence: {', '.join(f'`{i}`' for i in sorted(sentence.evidence_ids))}"
                )
            if sentence.citation is not None:
                lines.append(
                    f"   - Cites `{sentence.citation.anchor_id}` in document "
                    f"`{sentence.citation.content_digest[:16]}...`"
                )
                lines.append(f'   - Quoted: "{sentence.citation.excerpt}"')

    lines += ["", "---", "", *_status_lines(memo, signed), ""]
    return "\n".join(lines)


def render_html(memo: Memo, signed: SignedMemo | None = None) -> str:
    """Render a memo as standalone HTML.

    Everything user-facing goes through ``html.escape``. The memo carries policy
    excerpts and agent-authored prose, and an export that interpolated either
    into markup unescaped would be a second route by which case-derived text
    reaches a renderer, which is the whole class of problem the input firewall
    exists to close on the way in.
    """
    signed_off = _signature_covers(memo, signed)
    banner_class = "signed" if signed_off else "draft"
    banner = "SIGNED STATEMENT OF REASONS" if signed_off else WATERMARK

    body: list[str] = [
        "<!DOCTYPE html>",
        '<html lang="en"><head><meta charset="utf-8">',
        f"<title>{html.escape(memo.memo_id)}</title>",
        "<style>",
        "body{font-family:system-ui,sans-serif;max-width:48rem;margin:2rem auto;padding:0 1rem}",
        ".draft{background:#fde68a;border:2px solid #b45309;color:#7c2d12;"
        "padding:.75rem;font-weight:700;position:sticky;top:0}",
        ".signed{background:#bbf7d0;border:2px solid #15803d;color:#14532d;"
        "padding:.75rem;font-weight:700}",
        "dt{font-weight:600;margin-top:.5rem}code{word-break:break-all}",
        "</style></head><body>",
        f'<div class="{banner_class}">{html.escape(banner)}</div>',
        f"<h1>Statement of reasons: {html.escape(memo.memo_id)}</h1>",
        "<dl>",
        f"<dt>Case</dt><dd><code>{html.escape(memo.case_id)}</code></dd>",
        f"<dt>Subject</dt><dd><code>{html.escape(memo.subject_id)}</code></dd>",
        f"<dt>Evidence pack</dt><dd><code>{html.escape(memo.pack_digest)}</code></dd>",
        f"<dt>Policy corpus</dt><dd><code>{html.escape(memo.corpus_version)}</code> "
        f"<code>{html.escape(memo.corpus_sha256)}</code></dd>",
        "<dt>Use of automated means (Art. 17(3)(c))</dt><dd>"
        f"detection automated: {'yes' if memo.automated_means.detection_automated else 'no'}; "
        f"decision: <code>{html.escape(memo.automated_means.decision.value)}</code>; "
        f"drafted by: <code>{html.escape(memo.automated_means.drafted_by)}</code></dd>",
        "</dl>",
    ]

    if signed_off:
        assert signed is not None
        body += [
            "<dl>",
            f"<dt>Signed by</dt><dd><code>{html.escape(signed.signature.analyst_id)}</code></dd>",
            f"<dt>Signed at</dt><dd>{html.escape(signed.signature.signed_ts.isoformat())}</dd>",
            f"<dt>Signature</dt><dd><code>{html.escape(signed.signature.signature_hash)}</code>"
            "</dd>",
            "</dl>",
        ]
    elif signed is not None:
        body.append(
            "<p><strong>A signature was supplied and does not cover this memo.</strong> "
            f"It is over <code>{html.escape(signed.signature.subject_hash[:16])}...</code> "
            f"and this memo digests to <code>{html.escape(memo.content_digest[:16])}...</code>."
            "</p>"
        )

    for role in SentenceRole:
        sentences = [s for s in memo.sentences if s.role is role]
        if not sentences:
            continue
        body.append(f"<h2>{html.escape(_ROLE_HEADINGS[role])}</h2><ol>")
        for sentence in sentences:
            item = [f"<li>{html.escape(sentence.text)}"]
            if sentence.evidence_ids:
                joined = ", ".join(sorted(sentence.evidence_ids))
                item.append(f"<br><small>Evidence: <code>{html.escape(joined)}</code></small>")
            if sentence.citation is not None:
                item.append(
                    f"<br><small>Cites <code>{html.escape(sentence.citation.anchor_id)}</code>: "
                    f"&ldquo;{html.escape(sentence.citation.excerpt)}&rdquo;</small>"
                )
            body.append("".join(item) + "</li>")
        body.append("</ol>")

    body.append(f'<div class="{banner_class}">{html.escape(banner)}</div>')
    body.append("</body></html>")
    return "\n".join(body) + "\n"


def write_memo_markdown(memo: Memo, path: Path, signed: SignedMemo | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_markdown(memo, signed), encoding="utf-8", newline="\n")


def write_memo_html(memo: Memo, path: Path, signed: SignedMemo | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_html(memo, signed), encoding="utf-8", newline="\n")
