# SPDX-License-Identifier: MIT
"""STEP-07 D2: deterministic rendering of the sensitivity curves.

This module draws. It computes nothing. Every number it puts on a canvas came
from ``measurement.sensitivity`` and was already written to disk as JSON and
CSV, which is the split the phase's reproducibility claim depends on:

* **the curve data is the byte-stable artifact.** Identical across runs and
  across machines, and it is what a reader regenerates the numbers from.
* **a PNG is a rendering of that data.** Asserted byte-identical across two
  renders in the same environment. Cross-version byte-stability is **not**
  claimed, because it would belong to a version pin rather than to this code,
  and a suite that reddens on every matplotlib upgrade would be reporting the
  pin's stability as though it were ours.

STEP-07 3.4 asks for figures "regenerable byte-stable or hash-stable (documented
which)". The answer is: byte-stable in environment, for the reason above, and
the data behind them byte-stable everywhere.

How determinism is obtained
---------------------------
Three things, all of which matter:

* **The Agg canvas is constructed directly**, rather than going through pyplot
  and a global backend switch. No interpreter-wide state is touched, so
  rendering here cannot depend on what some other importer did to the backend,
  and no figure is left in pyplot's registry.
* **Every style value is passed explicitly.** A user's ``matplotlibrc`` must not
  be able to change the output, so nothing is inherited: size, dpi, colours,
  line widths and fonts are all set here.
* **The auto-generated PNG metadata is suppressed.** The Agg PNG writer injects
  a ``Software`` key when none is given, and it carries the matplotlib version.
  Two renders under one version agree, but the field is exactly the thing that
  would make bytes differ across an upgrade for no visible reason.
  ``FigureCanvasAgg.print_png`` documents the escape: "If 'Software' is not
  given, an autogenerated value for Matplotlib will be used. This can be removed
  by setting it to *None*." Verified against matplotlib 3.11.1, the version in
  this environment.
"""

import textwrap
from collections.abc import Mapping, Sequence
from pathlib import Path

from matplotlib.axes import Axes
from matplotlib.backends.backend_agg import FigureCanvasAgg
from matplotlib.figure import Figure

from ts_sentry.measurement.sensitivity import Curve

__all__ = [
    "FIGURE_DPI",
    "FIGURE_SIZE",
    "PLOTTED_SERIES",
    "render_curve",
    "render_curves",
]

FIGURE_DPI = 120
FIGURE_SIZE = (9.0, 5.5)
"""Fixed figure geometry. Any value would do; being fixed is what matters."""

_SUPPRESS_GENERATED_METADATA: Mapping[str, str | None] = {"Software": None}
"""See the module docstring. Removes the version-bearing auto key."""

_SERIES_COLOURS = (
    "#1f4e79",
    "#b3541e",
    "#3d7d3f",
    "#7a3d7a",
    "#8a6d1f",
)
"""An explicit cycle, so the colour of a series does not depend on a stylesheet."""

_INDICATOR_COLOURS = ("#c62828", "#6a1b9a")
"""Distinct shading per indicator, so two overlapping failure regions stay
tellable apart rather than compounding into one darker band."""

PLOTTED_SERIES: Mapping[str, tuple[tuple[str, ...], tuple[str, ...]]] = {
    "ci_width_vs_sample_size": (
        ("analytic_half_width", "realised_half_width", "point_estimate"),
        ("validity_holds",),
    ),
    "bias_vs_rater_quality": (
        (
            "true_vvr",
            "estimate_panel_1",
            "estimate_panel_3",
            "half_width_panel_1",
            "half_width_panel_3",
        ),
        ("covers_truth_panel_1", "covers_truth_panel_3"),
    ),
    "policy_scope_expansion": (("true_rate", "estimate"), ("is_faithful_vvr",)),
}
"""Which series are drawn as values, and which are indicators.

Split explicitly rather than inferred, because putting them on one axis would be
a lie about scale: ``validity_holds`` is 0 or 1 and the widths beside it are
around 0.001, so an automatic renderer would flatten every real series into the
x-axis. Indicators are drawn as shading and annotation instead.
"""


def _render_note(axes: Axes, curve: Curve) -> None:
    """Draw the caveat in its own axes at the foot of the figure.

    Its own axes rather than a floating ``figure.text`` because constrained
    layout reserves space for artists it owns and not for free text. The first
    version of this used floating text and the note printed straight through the
    plot area and the x tick labels. A caveat nobody can read is a caveat that is
    not there.
    """
    axes.axis("off")
    axes.text(
        0.5,
        0.9,
        "\n".join(textwrap.wrap(curve.note, 120)),
        ha="center",
        va="top",
        fontsize=7.5,
        color="#404040",
        linespacing=1.45,
    )


def _render_line(axes: Axes, curve: Curve) -> None:
    values, indicators = PLOTTED_SERIES[curve.name]

    xs = [point.x for point in curve.points]
    for index, name in enumerate(values):
        axes.plot(
            xs,
            [point.values[name] for point in curve.points],
            marker="o",
            markersize=4,
            linewidth=1.6,
            color=_SERIES_COLOURS[index % len(_SERIES_COLOURS)],
            label=name.replace("_", " "),
        )

    # Indicators become shaded spans rather than lines. A reader needs to see
    # *where* an assumption stopped holding, not a step function drawn over
    # series three orders of magnitude smaller.
    for offset, name in enumerate(indicators):
        colour = _INDICATOR_COLOURS[offset % len(_INDICATOR_COLOURS)]
        failing = [point.x for point in curve.points if point.values[name] == 0.0]
        for x in failing:
            step = _half_step(xs)
            axes.axvspan(x - step, x + step, color=colour, alpha=0.10)
        if failing:
            axes.plot([], [], color=colour, alpha=0.35, linewidth=8, label=f"{name} = 0")

    axes.set_xlabel(curve.x_label, fontsize=9)
    axes.set_ylabel(curve.y_label, fontsize=9)
    axes.grid(True, linewidth=0.4, alpha=0.4)
    axes.legend(fontsize=8, framealpha=0.9)
    axes.tick_params(labelsize=8)


def _half_step(xs: Sequence[float]) -> float:
    """Half the tightest gap between x values, so shaded spans never overlap."""
    if len(xs) < 2:
        return 0.5
    gaps = [abs(b - a) for a, b in zip(xs[:-1], xs[1:], strict=True)]
    return min(gaps) / 2.0


def _render_bars(axes: Axes, curve: Curve) -> None:
    values, indicators = PLOTTED_SERIES[curve.name]

    positions = list(range(len(curve.points)))
    width = 0.8 / len(values)
    for index, name in enumerate(values):
        axes.bar(
            [position + index * width for position in positions],
            [point.values[name] for point in curve.points],
            width=width,
            color=_SERIES_COLOURS[index % len(_SERIES_COLOURS)],
            label=name.replace("_", " "),
        )

    # The not-a-VVR marker rides on the tick label itself, so it cannot be
    # separated from the bar it qualifies by cropping the figure.
    labels = []
    for point in curve.points:
        suffix = ""
        for name in indicators:
            if point.values[name] == 0.0:
                suffix = "\n(NOT a VVR)"
        labels.append(point.label.replace("_", " ") + suffix)

    axes.set_xticks([position + width * (len(values) - 1) / 2 for position in positions])
    axes.set_xticklabels(labels, fontsize=8)
    axes.set_xlabel(curve.x_label, fontsize=9)
    axes.set_ylabel(curve.y_label, fontsize=9)
    axes.grid(True, axis="y", linewidth=0.4, alpha=0.4)
    axes.legend(fontsize=8, framealpha=0.9)
    axes.tick_params(labelsize=8)


def render_curve(curve: Curve, path: Path) -> Path:
    """Render one curve to a PNG, deterministically.

    Categorical curves, the ones whose points carry labels, are drawn as bars;
    the rest as lines. That is decided from the data rather than passed in, so a
    caller cannot render the policy-scope arms as a continuous line through
    three unrelated scopes.
    """
    if curve.name not in PLOTTED_SERIES:
        raise ValueError(
            f"no plot specification for curve {curve.name!r}; "
            "add one to PLOTTED_SERIES rather than letting a renderer guess"
        )

    figure = Figure(figsize=FIGURE_SIZE, dpi=FIGURE_DPI, layout="constrained")
    FigureCanvasAgg(figure)
    figure.suptitle(curve.name.replace("_", " "), fontsize=13, fontweight="bold")

    grid = figure.add_gridspec(2, 1, height_ratios=[5, 1])
    plot_area = figure.add_subplot(grid[0])
    note_area = figure.add_subplot(grid[1])

    categorical = any(point.label for point in curve.points)
    if categorical:
        _render_bars(plot_area, curve)
    else:
        _render_line(plot_area, curve)
    _render_note(note_area, curve)

    path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(
        path,
        format="png",
        dpi=FIGURE_DPI,
        metadata=dict(_SUPPRESS_GENERATED_METADATA),
    )
    return path


def render_curves(curves: Sequence[Curve], out_dir: Path) -> tuple[Path, ...]:
    """Render each curve as ``<out_dir>/<curve name>.png``."""
    return tuple(render_curve(curve, out_dir / f"{curve.name}.png") for curve in curves)
